### ISSUE TITLE
missing users.json file

### ISSUE THREAD

**Issue by gholadr** [longbkiter07/Triangle-Architecture#5]
`D/OkHttp: <-- 404 Not Found https://github.com/longbkiter07/Triangle-Architecture/users.json`

**Comment by longbkiter07** [comment]
I've just updated the domain. Please check again

**Comment by gholadr** [comment]
not seeing any changes being committed yet?

**Comment by gholadr** [comment]
for now i've changed `@GET("/users.json")`
 to 
 `@GET("http://android-architecture-1297.appspot.com/users.json")`
in
`me.silong.mvvm.data.api.HttpApiService`

**Comment by longbkiter07** [comment]
you shouldn't change anything, it's working. I've reconfigured my domain `silong.me`
